### PR TITLE
Improved demoaxi readability

### PR DESCRIPTION
**Pull request by pavel-demin**
Hello Dan,

Thank you very much for your articles on formal verification! They've helped me to [improve the AXI4-Lite interface of some of my cores](https://github.com/pavel-demin/red-pitaya-notes/commit/668c4496e9f0bd0529765d87556efdf39dcb96b0).

I'd like to propose an equivalent transformation of some of the logic in the demoaxi module that (in my opinion) improves its readability and makes it less scary.

What do you think?

Best regards,

Pavel

### CODE REVIEW

**Comment by ZipCPU** [comment]
Pavel,
Thank you so much for your proposal!  Some comments, though:

- I like what you've done with adding comments and removing the xresp code.  I'll merge these shortly

- I've noticed that you've used a lot of bit-wise negation when you intend logical negation.  While
  the two are implemented identically for a single bit, the are conceptually very different operations.

- The same applies to bit-wise versus the logical OR operator.

- Further, by separating the logic from the blocks that use them, using your `*_done` signals, it's
  no longer nearly as clear what's going on, and it's a bit harder to do a quick logic count by eye.

- In some cases, the `*_done` signal indicates that the channel isn't stalled, and in other
  cases it indicates that it is.  As an example, `axi_ar_done` is equivalent to `valid || !ready`
  whereas `axi_r_done` is equivalent to `!valid || ready`.

The extra in-line documentation is helpful, and I can merge that shortly.

Dan

**Comment by ZipCPU** [comment]
Ok, now that I think about it, and the more I think about it, I'm actually starting to like your ideas above.

I might just change your names, though, to something I think matches the description better.

Thanks!

Dan

**Comment by ZipCPU** [comment]
Feel free to check out my version [here](https://github.com/ZipCPU/wb2axip/commit/66eba84f54fa9973e45ef96dd8a9aa444489abe1).  The biggest changes were:

1. I didn't think `done` was sufficiently descriptive.  Instead I used names like `write_address_valid` and `write_response_stall`.  The write response stall signal is the complement of your done signal IIRC.

2. You simplified things even further.  I'm not certain I could explain those changes well on the blog, so I wan't quite as aggressive.  I think the synthesizer will create the same logic either way, although I haven't checked.

3. I now have updates to make to the blog article, to make certain it still matches this code.  Expect those changes soon.

Dan

**Comment by pavel-demin** [comment]
Thank you for updating the demoaxi module and for adding more comments! I agree that `write_address_valid` and` write_response_stall` are more descriptive than the names I originally suggested.

I think that the following two expressions on lines [276](https://github.com/ZipCPU/wb2axip/blob/master/rtl/demoaxi.v#L276) and [297](https://github.com/ZipCPU/wb2axip/blob/master/rtl/demoaxi.v#L297)
```
axi_awready <= ((axi_awready)&&(!S_AXI_AWVALID));

axi_wready <= (axi_wready)&&(!S_AXI_WVALID);
```
can also be replaced with
```
axi_awready <= !valid_write_address;

axi_wready <= !valid_write_data;
```
to make them more consistent with the expressions on lines [268](https://github.com/ZipCPU/wb2axip/blob/master/rtl/demoaxi.v#L268) and [289](https://github.com/ZipCPU/wb2axip/blob/master/rtl/demoaxi.v#L289).

**Comment by ZipCPU** [comment]
You are right, they can be replaced as you suggest.

I'm wondering how easily understandable they will be to a beginner if I do so, however.

**Comment by pavel-demin** [comment]
I'm not sure if I qualify as a beginner. So, the following is not to argue with you, just to give some feedback.

I was not patient enough to very carefully read all the explanations of the code in the the 'Read Channel Processing' and 'Write processing' sections. I read them rather superficially and quickly switched to playing with [demoaxi.v](https://github.com/ZipCPU/wb2axip/blob/685c8068473e6e5b745f479093b80091e572e052/rtl/demoaxi.v).

I tried to understand the high-level write processing algorithm, but without much success. Then I started transforming `if/then/else` blocks into logical expressions and grouping similar expressions. After several iterations, I obtained the following code:
```
  assign int_awdone_wire = ~int_awready_reg | s_axi_awvalid;
  assign int_wdone_wire = ~int_wready_reg | s_axi_wvalid;
  assign int_bdone_wire = ~int_bvalid_reg | s_axi_bready;

  assign int_we_wire = int_awdone_wire & int_wdone_wire & int_bdone_wire;

  assign int_awaddr_wire = int_awready_reg ? s_axi_awaddr : int_awaddr_reg;
  assign int_wdata_wire = int_wready_reg ? s_axi_wdata : int_wdata_reg;
  assign int_wstrb_wire = int_wready_reg ? s_axi_wstrb : int_wstrb_reg;

  always @*
  begin
    int_awaddr_next = int_awaddr_reg;
    int_awready_next = ~int_awdone_wire | (int_wdone_wire & int_bdone_wire);
    int_wdata_next = int_wdata_reg;
    int_wstrb_next = int_wstrb_reg;
    int_wready_next = ~int_wdone_wire | (int_awdone_wire & int_bdone_wire);
    int_bvalid_next = ~int_bdone_wire | (int_awdone_wire & int_wdone_wire);

    if(int_awready_reg)
    begin
      int_awaddr_next = s_axi_awaddr;
    end

    if(int_wready_reg)
    begin
      int_wdata_next = s_axi_wdata;
      int_wstrb_next = s_axi_wstrb;
    end
  end
```

Looking at it, I explained to myself the high-level algorithm of read and write processing as follows:

- there are 2 independent groups of channels: read related and write related
- there are 2 read related channels and 3 write related channels
- both master and slave can accept, initiate or block transactions on each channel using their output `*ready`/`*valid` ports
- slave shouldn't accept or initiate a transaction if there are blocked transactions on other channels in the same group
- slave shouldn't read/write data from/to its internal memory if there are blocked transactions in the corresponding group

**Pull request closed without merging**
